import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { NavbarDemo } from "../components/Nav"
import Footer from "../components/Footer"
import SmoothScrollProvider from "../components/SmoothScrollProvider"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "ghee bazar",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SmoothScrollProvider>
          <NavbarDemo />
          {children}
          <Footer />
          <Toaster/>
        </SmoothScrollProvider>
      </body>
    </html>
  )
}
